urls:
  base_url: https://somehost.ru

timeouts:
  implicit_timeout: 1
  cookie_expire: 1500

users:
  developer:
    role: role
    login: login
    password: password
    description: description
    space: space
    id: 201
  admin:
    role: role
    login: login
    password: password
    description: description
    space: None
    id: 135

defaults:
  password: password
  session: session

paths:
  chromedriver_path: path

moon:
  user: user
  password: password
  host: host
