urls:
  base_url: url

timeouts:
  implicit_timeout: 1
  cookie_expire: 1500

users:
  developer:
    login: login
    password: pass
    description: пользователь с ролью разработчик
    session: session
    space: space
    space_port_2001: space_port_2001

default_password:
  create_application: pass

paths:
  chromedriver_path: path_ti_chromdriver
